### ISSUE TITLE
Update to 1.21.4 Please

### ISSUE THREAD

**Issue by sternschnaube** [TheDreamer123/They-Are-Multiplying#1]
Hello, I was testing the mod right now - wanted to breed a Husk and server was crashing with this error.
However, the mod loads fine without any problems.

I have one question - I was not digging yet into the files. Is it possible to breed two mobs and this would results into a different kind of mob? My idea is, I would like to breed two Endermilbs and spawn this way the Ender Dragon... 😬

Encountered an unexpected exception
java.lang.NoSuchFieldError: field_11145
        at net.minecraft.class_1642.isBreedingItem(class_1642.java:736) ~[server-intermediary.jar:?]
        at net.minecraft.class_1308.handler$zih000$interactMobInject(class_1308.java:1623) ~[server-intermediary.jar:?]
        at net.minecraft.class_1308.method_5992(class_1308.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_1308.method_5688(class_1308.java:1156) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_7287(class_1657.java:1089) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244$1.method_33897(class_3244.java:1581) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244$1.method_34219(class_3244.java:1592) ~[server-intermediary.jar:?]
        at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12062(class_3244.java:1574) ~[server-intermediary.jar:?]
        at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[server-intermediary.jar:?]
        at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:787) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:166) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:769) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:763) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:747) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:680) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by TheDreamer123** [comment]
I'm pretty sure that's a problem with the tags.
Will look into it and reach out to you once it's fixed.

Also no, you can't, but that could be done.

**Comment by venaminecraft** [comment]
Thank you 😊
